version: '3'

services:
  nginx:
    container_name: emb3rs-nginx
    build:
      context: ./docker/
      dockerfile: Dockerfile
      args:
        ENABLED_MODULES: brotli
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_HOST='${APP_HOST:?err}'
    depends_on:
      - app

  app:
    image: emb3rs/platform
    container_name: emb3rs-platform
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NOVA_USERNAME: '${NOVA_USERNAME:?err}'
        NOVA_PASSWORD: '${NOVA_PASSWORD:?err}'

networks:
  default:
    external:
      name: network_emb3rs
