version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: embers-nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/certs:/etc/nginx/certs
    environment:
      - NGINX_HOST='${APP_HOST:?err}'
    networks:
      - embers

  app:
    image: embers/app
    container_name: embers-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NOVA_USERNAME: '${NOVA_USERNAME:?err}'
        NOVA_PASSWORD: '${NOVA_PASSWORD:?err}'
    volumes:
      - '.:/var/www/html'
    networks:
      - embers
    depends_on:
      - pgsql

  pgsql:
    image: 'postgres:13'
    container_name: embers-pgsql
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'emberspgsql:/var/lib/postgresql/data'
    networks:
      - embers
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE}",
          "-U",
          "${DB_USERNAME}"
        ]
      retries: 3
      timeout: 5s

networks:
  embers:
    external:
      name: embers_network

volumes:
  emberspgsql:
    driver: local
