<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cf/cf.proto

namespace Cf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cf.CharacterizationOutput</code>
 */
class CharacterizationOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string stream = 1;</code>
     */
    private $stream = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stream
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cf\Cf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string stream = 1;</code>
     * @return string
     */
    public function getStream()
    {
        return $this->stream;
    }

    /**
     * Generated from protobuf field <code>string stream = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStream($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream = $var;

        return $this;
    }

}

