<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cf/cf.proto

namespace Cf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cf.CharacterizationSinkOutput</code>
 */
class CharacterizationSinkOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string hot_stream = 1;</code>
     */
    private $hot_stream = '';
    /**
     * Generated from protobuf field <code>string cold_stream = 2;</code>
     */
    private $cold_stream = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hot_stream
     *     @type string $cold_stream
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cf\Cf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string hot_stream = 1;</code>
     * @return string
     */
    public function getHotStream()
    {
        return $this->hot_stream;
    }

    /**
     * Generated from protobuf field <code>string hot_stream = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHotStream($var)
    {
        GPBUtil::checkString($var, True);
        $this->hot_stream = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cold_stream = 2;</code>
     * @return string
     */
    public function getColdStream()
    {
        return $this->cold_stream;
    }

    /**
     * Generated from protobuf field <code>string cold_stream = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setColdStream($var)
    {
        GPBUtil::checkString($var, True);
        $this->cold_stream = $var;

        return $this;
    }

}

