<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cf/cf.proto

namespace Cf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cf.ConvertSinkOutput</code>
 */
class ConvertSinkOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string all_sinks_info = 1;</code>
     */
    private $all_sinks_info = '';
    /**
     * Generated from protobuf field <code>string n_demand_list = 2;</code>
     */
    private $n_demand_list = '';
    /**
     * Generated from protobuf field <code>string teo_demand_factor_group = 3;</code>
     */
    private $teo_demand_factor_group = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $all_sinks_info
     *     @type string $n_demand_list
     *     @type string $teo_demand_factor_group
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cf\Cf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string all_sinks_info = 1;</code>
     * @return string
     */
    public function getAllSinksInfo()
    {
        return $this->all_sinks_info;
    }

    /**
     * Generated from protobuf field <code>string all_sinks_info = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAllSinksInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->all_sinks_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string n_demand_list = 2;</code>
     * @return string
     */
    public function getNDemandList()
    {
        return $this->n_demand_list;
    }

    /**
     * Generated from protobuf field <code>string n_demand_list = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNDemandList($var)
    {
        GPBUtil::checkString($var, True);
        $this->n_demand_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string teo_demand_factor_group = 3;</code>
     * @return string
     */
    public function getTeoDemandFactorGroup()
    {
        return $this->teo_demand_factor_group;
    }

    /**
     * Generated from protobuf field <code>string teo_demand_factor_group = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTeoDemandFactorGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->teo_demand_factor_group = $var;

        return $this;
    }

}

