<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cf/cf.proto

namespace Cf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cf.ConvertSourceInput</code>
 */
class ConvertSourceInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string platform = 1;</code>
     */
    private $platform = '';
    /**
     * Generated from protobuf field <code>string gis_module = 2;</code>
     */
    private $gis_module = '';
    /**
     * Generated from protobuf field <code>string cf_module = 3;</code>
     */
    private $cf_module = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $platform
     *     @type string $gis_module
     *     @type string $cf_module
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cf\Cf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string platform = 1;</code>
     * @return string
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>string platform = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gis_module = 2;</code>
     * @return string
     */
    public function getGisModule()
    {
        return $this->gis_module;
    }

    /**
     * Generated from protobuf field <code>string gis_module = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGisModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->gis_module = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cf_module = 3;</code>
     * @return string
     */
    public function getCfModule()
    {
        return $this->cf_module;
    }

    /**
     * Generated from protobuf field <code>string cf_module = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCfModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->cf_module = $var;

        return $this;
    }

}

