<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager/manager.proto

namespace GPBMetadata\Manager;

class Manager
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Manager\Models\ManagerResponses::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afc010a156d616e616765722f6d616e616765722e70726f746f12076d61" .
            "6e6167657232d1010a0d4d616e616765724d6f64756c6512560a0f537461" .
            "727453696d756c6174696f6e121f2e6d616e616765722e53746172745369" .
            "6d756c6174696f6e526571756573741a202e6d616e616765722e53746172" .
            "7453696d756c6174696f6e526573706f6e7365220012680a155374617274" .
            "436861726163746572697a6174696f6e12252e6d616e616765722e537461" .
            "7274436861726163746572697a6174696f6e526571756573741a262e6d61" .
            "6e616765722e5374617274436861726163746572697a6174696f6e526573" .
            "706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

